/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.ui;

/**
 *
 * @author Denisse Bailon
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        dpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConf = new javax.swing.JMenu();
        menuRegistro = new javax.swing.JMenu();
        itemUsuario = new javax.swing.JMenuItem();
        itemEmpleado = new javax.swing.JMenuItem();
        itemProveedor = new javax.swing.JMenuItem();
        menuArticulo = new javax.swing.JMenuItem();
        menuFactura = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpEscritorio.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        menuConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/ejecuta-la-configuracion-artes-icono-4790-32.png"))); // NOI18N
        menuConf.setText("CONFIGURACION");
        jMenuBar1.add(menuConf);

        menuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/notas-adhesivas-icono-3917-32.png"))); // NOI18N
        menuRegistro.setText("REGISTRAR");

        itemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/anadir-usuario-icono-4000-16.png"))); // NOI18N
        itemUsuario.setText("USUARIO");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        menuRegistro.add(itemUsuario);

        itemEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/usuario-administrador-personal-icono-9746-16.png"))); // NOI18N
        itemEmpleado.setText("EMPLEADO");
        itemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadoActionPerformed(evt);
            }
        });
        menuRegistro.add(itemEmpleado);

        itemProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/el-informe-del-usuario-icono-9444-16.png"))); // NOI18N
        itemProveedor.setText("PROVEEDOR");
        itemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedorActionPerformed(evt);
            }
        });
        menuRegistro.add(itemProveedor);

        menuArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/pc-de-escritorio-de-la-computadora-icono-8780-16.png"))); // NOI18N
        menuArticulo.setText("ARTICULO");
        menuRegistro.add(menuArticulo);

        jMenuBar1.add(menuRegistro);

        menuFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/factura-bill-icono-9586-32.png"))); // NOI18N
        menuFactura.setText("FACTURA");
        jMenuBar1.add(menuFactura);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/cerrar-borrar-la-salida-icono-8537-32.png"))); // NOI18N
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemProveedorActionPerformed

    private void itemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEmpleadoActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrMenu().setVisible(true);
                FrMenu menu = new FrMenu();
                menu.setExtendedState(MAXIMIZED_BOTH);
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JMenuItem itemEmpleado;
    private javax.swing.JMenuItem itemProveedor;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuArticulo;
    private javax.swing.JMenu menuConf;
    private javax.swing.JMenu menuFactura;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
